### ISSUE TITLE
Announce release on the OxCOVID19 Project page

### ISSUE THREAD

**Issue by aezarebski** [como-ph/oxcovid19#29]
If @ernestguevarra agrees, once the `v0.1.2` gets released it would be nice to include this on the [news](https://covid19.eng.ox.ac.uk/news.html) page of the project.

**Comment by ernestguevarra** [comment]
Dear maintainer,

thanks, package oxcovid19_0.1.2.tar.gz is on its way to CRAN.

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-ix86+x86_64
Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
  Maintainer: 'Ernest Guevarra <ernest@guevarra.io>'
